### ISSUE TITLE
After updated to emacs 26.1: Request failed: args-out-of-range

### ISSUE THREAD

**Issue by tareefdev** [ternjs/tern#967] opened 2018-06-01 15:14 UTC
I updated my emacs to 26.1, now when I opened a `.js` file, the `tern` doesn't work and print the following message to echo area:

    Request failed: ((args-out-of-range [cl-struct-url http nil nil 127.0.0.1 40265 / nil nil nil nil t] 12))

I downgrade again to `25.x` and tern just works fine with it!

**Comment by ybiquitous** [comment] 2018-06-16 13:57
Maybe duplicate of #965 😩

Workaround on [this comment](https://github.com/ternjs/tern/issues/965#issuecomment-388613700) may help you... 😐

**Comment by finalclass** [comment] 2018-07-04 08:30
I've removed tern from `~/.emacs.d/elpa/tern-XXXX`, restarted emacs and reinstalled it (I'm using `use-package`) and all works fine again

**Comment by ybiquitous** [comment] 2018-07-04 08:47
@finalclass Thanks a lot!!! 😄 All works fine, too!

**Closed** 2018-09-02 14:03 UTC
Labels: emacs
