### ISSUE TITLE
Completions not working for ES6 imports in tern_for_vim

### ISSUE THREAD

**Issue by mrdanimal** [ternjs/tern#657] opened 2015-09-30 19:26 UTC
I haven't been able to get completions working for es6 imported modules, and after searching through the issues, I see lots of references to 'tern-es6'. #612 implies that tern-es6 is a completely different binary, but I'm not sure because there's no documentation mentioning it. If it is a different package, where is it located and how can I install it? If it's not, this is the `.tern-project` file I'm using:
```
{
  "libs": [ "browser", "ecma6" ],
  "plugins": {
    "node": {},
    "complete_strings": {},
    "es_modules": {}
  }
}
```

CommonJS `require`s work fine. I can also provide the server logs, if that would help. Thanks!

**Comment by marijnh** [comment] 2015-10-07 10:08
There is no different binary. Just get the latest code and run `tern`. You don't have to include `ecma6` in your project config—it is automatically included, but other than that it looks fine. If the server crashes, try upgrading.

**Comment by mrdanimal** [comment] 2015-10-12 23:34
Thanks. The server wasn't crashing, but I upgraded anyway, and now if I import modules that I create, they get completions, but if I import anything in `/node_modules`, they still never work. Does the ES6 `import` syntax only work for modules that actually use the ES6 `export` syntax, but not modules that use `module.exports`?

**Comment by marijnh** [comment] 2015-10-16 13:06
That should also work. Could you create a minimal test case that I can debug?

**Comment by anvaka** [comment] 2015-10-17 05:59
Interesting, I also noticed this. In my case however the tern node server is a zombie process (Z+ status in the `ps aux`). Trying to debug/reproduce it to get more info

**Comment by anvaka** [comment] 2015-10-17 06:27
Looks like it doesn't like when a module exports empty object:

``` js
// config.js
export default {}
```

It doesn't really matter how or what you use in other file. E.g. bar.js:

``` js
import * as config from './config.js';

function foo() {}
foo();
```

When your cursor is on the last line TernDef will not go to foo definition.

**Comment by eddiezane** [comment] 2015-10-23 20:10
It seems that it's working when you `import * as foo from 'foo'` as opposed  to `import foo from 'foo'`.

Example with [body-parser](https://github.com/expressjs/body-parser) installed via `npm install body-parser`.

<img width="602" alt="screen shot 2015-10-23 at 1 07 48 pm" src="https://cloud.githubusercontent.com/assets/959573/10703793/5298c666-7987-11e5-97ea-652ebd2a9600.png">

<img width="531" alt="screen shot 2015-10-23 at 1 08 44 pm" src="https://cloud.githubusercontent.com/assets/959573/10703795/5673e98c-7987-11e5-9746-46bfea09a19e.png">

**Comment by marijnh** [comment] 2015-10-27 20:45
@anvaka The issue you saw was an Acorn bug. Fixed in attached patch.

**Closed by marijnh** 2015-10-27 20:45 UTC

**Comment by budi** [comment] 2016-09-28 17:46
> Nearly twelve moons passed
> The one tool I use dearly
> Exacerbating

This haiku is a cry for help to make tern include acorn ^4.0.3 as dependency because I love it so much I keep editing my `YouCompleteMe` and `tern_for_vim` package again and again and again so I can embrace the future (read: be lazy) by typing `import` as it is.

Much love,
Budi.

**Comment by marijnh** [comment] 2016-09-29 08:20
Isn't the fix to this issue already in Acorn releases way older than 4.0.3? I can bump the Acorn dependency, and definitely will on the next release, but I don't see how that is supposed to be related to this issue.

**Comment by budi** [comment] 2016-09-30 09:17
I was brought here by the same issue as everyone here, had the  same symptoms and everything. No worries, then :)

**Comment by imtiazwazir** [comment] 2016-11-18 09:58
+1

**Comment by ViggoV** [comment] 2019-04-01 14:18
Weird! I am having a similar issue, but it turns out it's only the first occurence where the completions are missing.

![Skærmbillede 2019-04-01 kl  16 15 16](https://user-images.githubusercontent.com/3153568/55334418-8505f380-5499-11e9-8079-7b03de0ca47e.png)

![Skærmbillede 2019-04-01 kl  16 15 42](https://user-images.githubusercontent.com/3153568/55334443-92bb7900-5499-11e9-8aec-c433aee044dc.png)
